<footer class="vu5">
        <div class="vu6">
            <div class="vu7">
                <div class="vu8">
                    <h4>Company</h4>
                    <ul>
                        <li><a href="index.php">Home</a></li>
                        <li><a href="product.php">Product</a></li>
                        <li><a href="enquire.php">Enquire</a></li>
                        <li><a href="about.php">About</a></li>
                        <li><a href="enhancements.php">Enhancements</a></li>
                    </ul>
                </div>
                <div class="vu8">
                    <h4>Get Help</h4>
                    <ul>
                        <li><a href="#">Our Services</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
                <div class="vu8">
                    <h4>Online courses</h4>
                    <ul>
                        <li><a href="#">Computer Science</a></li>
                        <li><a href="#">Business</a></li>
                        <li><a href="#">Media & Communication</a></li>
                    </ul>
                </div>
                <div class="vu8">
                    <h4>Follow us</h4>
                    <div class="vu9">
                        <a href="#"><i class="fa-brands fa-facebook"></i></a>
                        <a href="#"><i class="fa-brands fa-twitter"></i></a>
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                        <a href="#"><i class="fa-brands fa-linkedin"></i></a>
                    </div>
                    <div class="vu10">
                        <p class="vu11"><i class="fa-solid fa-copyright"></i> 2023 TCAMV. ALL RIGHTS RESERVED.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>