        <div class="vu3">
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="product.php">Product</a></li>
                <li><a href="payment.php">Enquire</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="enhancements2.php">Enhancements</a></li>
            </ul>
        </div>
        <div class="vu4">
            <a href=""><i class="fa-solid fa-magnifying-glass"></i></a>
            <a href=""><i class="fa-solid fa-cart-shopping"></i></a>
            <a href="login.php"><i class="fa-solid fa-user"></i></a>
        </div>
    </nav>
</header>
